version: 2.1
executorType: machine
jobs:
  kp-build:
    docker:
      - image: circleci/openjdk:14-jdk-buster-node-browsers-legacy
      - image: circleci/redis:latest
    steps:
      - checkout
      - restore_cache:
          key: kp-dependency-cache-{{ checksum "pom.xml" }}
      - run:
          name: Setup VM and Build
          command: bash vmsetup.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
workflows:
  version: 2.1
  workflow:
    jobs:
      - kp-build
