name: search job workflow

on:
  push:
    branches:
      - '*'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 14
          architecture: x64

      - name: Install imagemagick
        run: |
          sudo apt-get update --allow-releaseinfo-change || sudo apt-get update --allow-releaseinfo-change
          sudo apt-get install -y imagemagick
      - name: Execute coverage report
        run: |
          mvn clean scoverage:report -DCLOUD_STORE_GROUP_ID=$CLOUD_STORE_GROUP_ID -DCLOUD_STORE_ARTIFACT_ID=$CLOUD_STORE_ARTIFACT_ID -DCLOUD_STORE_VERSION=$CLOUD_STORE_VERSION
      - name: Save test results
        run: |
          mkdir -p ~/test-results/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
        if: always()
      - name: Save Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: kp-jobs-dependency-cache-${{ hashFiles('pom.xml') }}
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ~/test-results
      - name: Run SonarQube analysis
        run: |
          mvn -X sonar:sonar -Dlog4j.configuration=./logs sonar:sonar -Dsonar.projectKey=project-sunbird_knowledge-platform-jobs -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.exclusions=**/cert-processor/** -Dsonar.scala.coverage.reportPaths=/home/runner/work/kp/kp/target/scoverage.xml
